@Calculus.Web_HostAddress = http://localhost:5166


GET {{Calculus.Web_HostAddress}}/scenarios/
Accept: application/json

###

@scenarioId = d2269672-cd77-4b0e-bd02-29ddabafc580
GET {{Calculus.Web_HostAddress}}/scenarios/{{scenarioId}}
Accept: application/json

###
