@Calculus.Web_HostAddress = http://localhost:5166


GET {{Calculus.Web_HostAddress}}/scenarios/
Accept: application/json

###

@scenarioId = e39d5974-39a6-4c53-bdbd-763f75872b2c
GET {{Calculus.Web_HostAddress}}/scenarios/{{scenarioId}}
Accept: application/json

###

POST {{Calculus.Web_HostAddress}}/scenarios/
Content-Type: application/json
Accept: application/json

{
  "name": "Test Scenario"
}

###

POST {{Calculus.Web_HostAddress}}/users/
Content-Type: application/json
Accept: application/json

{
  "email": "Barbaros@gmail.com",
  "password": "Pass@word1"
}

###

POST {{Calculus.Web_HostAddress}}/users/login
Content-Type: application/json
Accept: application/json

{
  "email": "Barbaros.yurttagul@gmail.com",
  "password": "Pass@word1"
}
