// <auto-generated />
using System;
using Calculus.Scenarios;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calculus.Scenarios.Data.Migrations
{
    [DbContext(typeof(ScenarioDbContext))]
    [Migration("20250119210032_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Scenario")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Calculus.Scenarios.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Scenarios", "Scenario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e39d5974-39a6-4c53-bdbd-763f75872b2c"),
                            Author = "John Doe",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sample Scenario 1"
                        },
                        new
                        {
                            Id = new Guid("e39d5974-39a6-4c53-bdbd-763f75872b2d"),
                            Author = "Jane Doe",
                            CreatedAt = new DateTime(2023, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sample Scenario 2"
                        },
                        new
                        {
                            Id = new Guid("e39d5974-39a6-4c53-bdbd-763f75872b2e"),
                            Author = "John Doe",
                            CreatedAt = new DateTime(2023, 8, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sample Scenario 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
